### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by NHellFire** [NHellFire/py-osm-static-maps#1]
There's a few things left to do:

- [ ] Implement the /dynamic endpoint
- [ ] Make WebdriverPool browser-agnostic
- [ ] Add commandline arguments for WebdriverPool size
- [ ] Make WebdriverPool into a proper process manager (min/max workers, recycle after X requests/time)
- [ ] Skip grabbing a browser if `renderToHtml` is set as we don't need one

**Comment by sikmir** [comment]
macOS support would be nice.

**Comment by NHellFire** [comment]
> macOS support would be nice.

I've just managed to test that and pushed a fix. Can you retest and open a separate issue if it's still not working?

**Comment by sikmir** [comment]
> > macOS support would be nice.
> 
> I've just managed to test that and pushed a fix. Can you retest and open a separate issue if it's still not working?

It works now, thanks!
